<a href="https://colab.research.google.com/github/wjh818/Data_hwj/blob/main/Deep_Learning/0_numpy_%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

numpy는 내부적으로 c로 구현이 되어 있다. 수치에 관련된 프로그래밍을 할 때 일반 python보다 훨씬 빠르다.
특히, 배열 연산에 특화되어 있다.

In [ ]:
# 일반 파이썬 리스트를 numpy 배열화 (numpy 배열: ndarray)
py_list = [1, 2, 3]
arr1 = np.array(py_list)
arr1

array([1, 2, 3])

In [ ]:
# ndarray 타입 확인하기
type(arr1)

numpy.ndarray

In [ ]:
py_list = [ [1, 2, 3],
            [4, 5, 6] ]

arr2 = np.array(py_list)
type(arr2)

numpy.ndarray

numpy 에서는 숫자 배열을 만들기 위한 여러가지 함수를 제공한다.

---






# np.arange

In [ ]:
# np.arange 함수는 파이썬의 range 함수와 매우 흡사하다.
arr = np.arange(10) # 0 ~ 9 까지 들어있는 숫자 배열을 생성
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr = np.arange(1, 10) # 1 ~ 9 까지 들어있는 숫자 배열을 생성
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr = np.arange(1, 10, 2) # 1부터 9까지 2씩 띄워가면서 숫자 배열 생성
arr

array([1, 3, 5, 7, 9])

# 다차원 배열 만들기
* `np.zeros`
* `np.ones`
* `np.full`

## np.zeros
지정된 차원에 모든 원소를 0으로 채운다.

In [ ]:
np.zeros(5) # 1차원 배열에 5개의 0을 채운다.

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((4, 5)) # 4행 5열(2차원 배열)의 배열에 0을 채운다.

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.zeros((3, 4, 5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

## np.ones
지정한 차원에 모든 원소를 1로 채운다.

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.ones((4, 5)) * 3

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

## np.full
지정한 차원에 모든 원소를 원하는 숫자로 채운다.

In [ ]:
np.full((3, 4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

# 단위 행렬 만들기
* `np.eye`
* 단위 행렬 : 대각선 방향의 원소가 1이고, 나머지 원소는 0인 행렬

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

# 구간 나누기
* `np.linspace`

In [ ]:
np.linspace(1, 10, 3) # 1부터 10까지 2개의 구간 만들기

array([ 1. ,  5.5, 10. ])

In [ ]:
np.linspace(1, 10, 4)

array([ 1.,  4.,  7., 10.])

In [ ]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

# Random을 사용하기 위한 numpy
* 보통 랜덤한 배열은 딥러닝에서 매개변수의 초기화를 하기 위해 사용
* 딥러닝에서는 일반적으로 Xavier 초깃값, He 초깃값, 정규분포 초깃값을 계산해 준다.

## np.random.rand
* 완전한 랜덤 만들기 ( 정규분포나 균등분포가 아닌 랜덤값 )

In [ ]:
np.random.rand(2, 3) # 랜덤값을 채울 차원을 지정

array([[0.69695358, 0.22112954, 0.02953904],
       [0.86041101, 0.51437531, 0.34434607]])

## np.random.randn
* 정규분포 랜덤값 만들기

In [ ]:
np.random.randn(10)

array([-0.00458626, -0.06246228,  0.48817252,  0.26657474,  1.52376047,
       -1.34546895, -0.29781937, -1.48720269, -1.88007909, -0.58775771])

## np.random.uniform
* 균등분포 랜덤값 만들기

In [ ]:
np.random.uniform(1.0, 3.0, size=(4, 5)) # 1.0 ~ 3.0 까지 균등분포 랜덤값 생성

array([[2.59728779, 2.20523392, 2.00315387, 2.67915728, 1.48865042],
       [2.27643238, 1.97404593, 2.47665551, 2.48670657, 2.26721437],
       [2.24981178, 1.34366973, 1.86055642, 1.08872672, 1.44762697],
       [2.35411202, 1.88321438, 1.47019225, 2.64036122, 2.21422128]])

# 정수 랜덤 만들기
* `np.random.randint`

In [25]:
np.random.randint(1, 100, size=(5, )) # 1차원 배열의 원소 5개에 1 ~ 100까지의 랜덤값으로 채우기

array([32, 55, 30, 78, 74])

In [26]:
np.random.randint(1, 100, size=(5, 1)) # 2차원 배열에 랜덤 정수 채우기

array([[53],
       [55],
       [28],
       [67],
       [65]])

In [27]:
np.random.randint(1, 100, size=(3, 4, 5))

array([[[36,  4, 21, 41, 29],
        [82, 32, 51, 83, 40],
        [39, 15, 13, 32, 54],
        [16,  2, 73, 51, 13]],

       [[23, 60, 43, 49, 94],
        [34, 94, 67, 21, 42],
        [91,  3, 47, 95, 17],
        [96, 29,  8,  9, 23]],

       [[99, 24, 98, 46, 21],
        [13, 30, 13, 88, 38],
        [47, 51, 61, 41, 68],
        [21, 51, 20,  5, 77]]])

# 정수 랜덤 샘플링 하기
* `np.random.choice`
* 랜덤 샘플링 : 일정한 범위 내에서 필요한 정수를 랜덤으로 추출
* 미니배치를 만들 때 사용합니다.*이탤릭체 텍스트*

In [28]:
np.random.choice(100, size=(3, 4))

array([[83,  8, 14, 48],
       [57, 62, 29, 69],
       [15, 43, 74, 88]])

In [29]:
# 임의의 배열을 만들어서 그 안에서 랜덤하게 추출할 수 있도록 함
arr = np.arange(1, 6)

np.random.choice(arr, size=(2, 2), replace=False) # replace가 True면 원소를 중복 추출, False면 중복 추출 X

array([[4, 2],
       [1, 3]])

# 인덱스와 슬라이싱

In [30]:
arr = np.arange(1, 11).reshape(2, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [31]:
arr[0][2]

3

In [32]:
arr[0, 2]

3

In [33]:
arr[:, 2] # 2차원 배열 내에서 1차원 배열은 전체 선택, 0차원 스칼라값은 2번째 인덱스에 있는 것을 선택

array([3, 8])

In [34]:
arr = np.arange(1, 37).reshape(3, 4, 3)
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]],

       [[25, 26, 27],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

In [37]:
arr[:, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[13, 14],
        [16, 17]],

       [[25, 26],
        [28, 29]]])

In [42]:
arr[1:, 1:3, 1:]

array([[[17, 18],
        [20, 21]],

       [[29, 30],
        [32, 33]]])

# 배열의 차원과 형상
* 형상( `shape` )
* 차원수( `ndim` )

In [43]:
arr = np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
arr.shape

(3, 4)

In [45]:
arr.ndim

2

# 차원수 확장하기
* 항상 같은 예시는 아니지만, 보통은 이미지 분석( CNN )을 하기 위해 데이터를 전처리 하면서 사용 된다.
* tensorflow는 `tf.newaxis`를 활용, numpy는 `np.newaxis`를 활용해서 추가 차원을 만들어 낼 수 있다.

In [46]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
arr.shape

(3, 4)

In [48]:
tmp_arr = arr[np.newaxis, :, :, np.newaxis] # arr의 첫 번째와 마지막에 차원을 1씩 확장
tmp_arr

array([[[[ 0],
         [ 1],
         [ 2],
         [ 3]],

        [[ 4],
         [ 5],
         [ 6],
         [ 7]],

        [[ 8],
         [ 9],
         [10],
         [11]]]])

In [49]:
# 실제 데이터를 다룰 때는 실제 데이터를 보는 것이 아닌, shape만 보자..
tmp_arr.shape

(1, 3, 4, 1)

In [50]:
# 각 차원이 1인 차원 삭제하기
tmp_arr2 = np.squeeze(tmp_arr)
tmp_arr2.shape

(3, 4)

`spread` 연산자 활용하기
* 슬라이싱 도중에 특정 차원 부터는 전체를 선택할 때 사용한다.

In [53]:
tmp_arr3 = arr[np.newaxis, ..., np.newaxis] # ... -> spread 연산자
tmp_arr3.shape

(1, 3, 4, 1)

# 배열의 형상(shape) 바꾸기
* `np.newaxis`를 활용해서 축을 추가한다. (차원수를 늘린다.)

평탄화
* `ravel` : 원본 배열을 평탄화 시킨 참조배열을 만들어 낸다. (View 또는 Reference 를 만들었다 라고 표현한다.)
* `flatten` : 평탄화 시킨 **복사된** 배열을 만들어 낸다.

형상 변환
* `reshape`


In [54]:
x = np.arange(15).reshape(3, 5)
x.shape

(3, 5)

In [55]:
print("원본 x : \n{}".format(x))

원본 x : 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [56]:
temp = np.ravel(x)
print("ravel로 평탄화된 x의 shape : {}".format(x.shape))
print("ravel로 평탄화된 x : \n{}".format(temp))

ravel로 평탄화된 x의 shape : (3, 5)
ravel로 평탄화된 x : 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


`ravel`함수는 원본의 참조본을 만들어 낸다.

In [57]:
print(temp[0])

0


In [58]:
temp[0] = 100
print(x)

[[100   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]]


In [59]:
# flatten은 복사본을 만들어 낸다.
y = np.arange(15).reshape(3, 5)
temp2 = y.flatten()
print("원본 y : \n{}".format(y))
print("flatten으로 평탄화된 temp2의 shape : {}".format(temp2.shape))
print("flatten으로 평탄화된 temp2 : \n{}".format(temp2))

원본 y : 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
flatten으로 평탄화된 temp2의 shape : (15,)
flatten으로 평탄화된 temp2 : 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [60]:
temp2[0] = 100 # flatten을 활용해서 y의 복사본을 만들어 냈기 때문에 원본 y에는 영향을 미치지 않는다.
print(temp2)
print(y)

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


`reshape` 사용하기

In [61]:
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

`reshape` 팁 : `reshape` 함수 내의 모든 숫자를 곱했을 때 스칼라 원소의 개수와 같기만 하면 된다.

In [62]:
x.reshape(2, 5, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

`-1`을 `reshape`에 넣으면 남는 숫자를 자동으로 계산해 준다.

In [63]:
x.reshape(2, 2, -1) # 2 * 2 는 4니까, -1은 5를 의미하게 된다.

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [64]:
x.reshape(2, -1, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [65]:
x.reshape(3, -1) # 오류... 한쪽 차원의 수가 3이면 원소의 개수인 20만큼 딱 떨어지지 않기 때문에 오류

ValueError: ignored