<a href="https://colab.research.google.com/github/wjh818/Data_hwj/blob/main/Deep_Learning/3_%EB%8B%A4%EC%B0%A8%EC%9B%90_%EB%B0%B0%EC%97%B4%EC%9D%98_%EA%B3%84%EC%82%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 행렬의 내적 (행렬의 곱)

In [1]:
import numpy as np

In [2]:
A = np.array([ [1, 2],
               [3, 4] ])

B = np.array([ [5, 6],
               [7, 8] ])

print("A의 shape : {}".format(A.shape))
print("B의 shape : {}".format(B.shape))

A의 shape : (2, 2)
B의 shape : (2, 2)


위의 행렬에서 $A \times B$ 는 계산이 가능하다. A.shape[1]과 B.shape[0]이 같기 때문에

In [3]:
# numpy의 dot을 이용해 행렬의 내적을 구할 수 있다.
print(" A X B : \n{}\n".format( np.dot(A, B) ))
print(" B X A : \n{}".format( np.dot(B, A) ))

 A X B : 
[[19 22]
 [43 50]]

 B X A : 
[[23 34]
 [31 46]]


행열의 내적은 교환 법칙이 성립되지 않는다.

In [4]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[1, 2],
              [3, 4],
              [5, 6]])

print("행렬 A의 shape : {}".format(A.shape))
print("행렬 B의 shape : {}".format(B.shape))

행렬 A의 shape : (2, 3)
행렬 B의 shape : (3, 2)


In [5]:
print(" A X B : \n{}\n".format( np.dot(A, B) ))
print(" B X A : \n{}".format( np.dot(B, A) ))

 A X B : 
[[22 28]
 [49 64]]

 B X A : 
[[ 9 12 15]
 [19 26 33]
 [29 40 51]]


In [6]:
C = np.array([[1, 2],
              [3, 4]])

print("행렬 C의 shape : {}".format(C.shape))
print("행렬 A의 shape : {}".format(A.shape))

행렬 C의 shape : (2, 2)
행렬 A의 shape : (2, 3)


In [7]:
print(" A X C : \n{}".format( np.dot(A, C) )) # 오류

ValueError: ignored

In [8]:
print(" C X A : \n{}".format( np.dot(C, A) ))

 C X A : 
[[ 9 12 15]
 [19 26 33]]


차원 수가 다른 경우의 계산도 가능하다.

In [9]:
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

B = np.array([7, 8])

print("행렬 A의 shape : {}".format(A.shape))
print("행렬 B의 shape : {}".format(B.shape))

행렬 A의 shape : (3, 2)
행렬 B의 shape : (2,)


In [10]:
print(" A X B : \n{}".format( np.dot(A, B) ))

 A X B : 
[23 53 83]


In [11]:
print(" B X A : \n{}".format( np.dot(B, A) )) # 오류

ValueError: ignored