<a href="https://colab.research.google.com/github/wjh818/Data_hwj/blob/main/Deep_Learning/4_%ED%96%89%EB%A0%AC%EA%B3%BC_%EC%8B%A0%EA%B2%BD%EB%A7%9D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
X = np.array([1.0, 0.5])
W1 = np.array([[0.1, 0.3, 0.5], 
               [0.2, 0.4, 0.6]])  # 2개씩 입력을 받는 3개의 뉴런

B1 = np.array([0.1, 0.2, 0.3])  # 3개의 뉴련에 더해질 편향들

# 계산값 구하기
Z1 = np.dot(X, W1) + B1
Z1

array([0.3, 0.7, 1.1])

In [3]:
# 활성화 함수 준비
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

In [4]:
A1 = sigmoid(Z1)
A1

array([0.57444252, 0.66818777, 0.75026011])

In [5]:
W2 = np.array([[0.1, 0.4],
               [0.2, 0.5],
               [0.3, 0.6]]) # 3개의 입력을 받는 2개의 뉴런

B2 = np.array([0.1, 0.2])

print(A1.shape, W2.shape)

Z2 = np.dot(A1, W2) + B2
A2 = sigmoid(Z2)
A2

(3,) (3, 2)


array([0.62624937, 0.7710107 ])

In [7]:
# 출력층

# 항등함수
def identity_function(x):
    return x

W3 = np.array([[0.1, 0.3], 
               [0.2, 0.4]]) # 2개의 입력을 받는 2개의 뉴런

B3 = np.array([0.1, 0.2])

print(A2.shape, W3.shape)

(2,) (2, 2)


In [8]:
Z3 = np.dot(A2, W3) + B3
Y  = identity_function(Z3)
Y

array([0.31682708, 0.69627909])

최종 구현

In [11]:
def init_network():
    # 네트워크 초기화 과정
    # 네트워크가 초기화 되면 일반적으로 정규분포 * 0.01 정도의 랜덤값으로 초기화 한다.
    # 다른 방법으로 카이밍 히(He 초깃값) 또는 사비에르(Xavier) 초깃값을 사용한다. ( 활성화 함수에 따라 달라져요 )
    network = {}
    network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
    network['b1'] = np.array([0.1, 0.2, 0.3])
    network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
    network['b2'] = np.array([0.1, 0.2])
    network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
    network['b3'] = np.array([0.1, 0.2])
    
    return network
# 순전파 과정
def forward(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    
    z1 = np.dot(x, W1) + b1
    a1 = sigmoid(z1)
    
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)
    
    z3 = np.dot(a2, W3) + b3
    y  = identity_function(z3)
    
    return y

In [12]:
network = init_network()
x = np.array([1.0, 0.5])
y = forward(network, x)
print(y)

[0.31682708 0.69627909]
