<a href="https://colab.research.google.com/github/wjh818/Data_hwj/blob/main/Deep_Learning/5_%EC%B6%9C%EB%A0%A5%EC%B8%B5_%EC%84%A4%EA%B3%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 출력층의 활성화 함수
* 이진 분류(Binary Classification) : $softmax$, $sigmoid$ 함수를 주료 사용
* 다중 분류(Mulitple Classification) : $softmax$

보통 전천후 함수로 $softmax$ 함수를 주로 사용하는 추세이고, $sigmoid$를 출력층의 활성화 함수로 사용할 때는 **출력층의 뉴런은 한개로 설정**한다.

$$
y_k = \frac{exp(a_k)}{\sum_{i=1}^n exp(a_i)}

$$

In [2]:
# softmax 함수 구현하기 - 원리
import numpy as np

a = np.array( [0.3, 2.9, 4.0] )

# 분자 계산
exp_a = np.exp(a) # 모든 입력 신호에 대한 지수 함수 적용

# 분모 계산
sum_exp_a = np.sum(exp_a) # 모든 입력 신호에 대한 지수 함수의 합

y = exp_a / sum_exp_a
print("softmax 결괏값 : {}".format(y))

softmax 결괏값 : [0.01821127 0.24519181 0.73659691]


In [3]:
print("softmax 결괏값의 총 합 : {}".format(np.sum(y)))

softmax 결괏값의 총 합 : 1.0


$softmax$ 함수 직접 구현

In [4]:
def softmax(a):
  exp_a = np.exp(a)
  sum_exp_a = np.sum(exp_a)
  y = exp_a / sum_exp_a

  return y

In [5]:
# 위에와 결과가 똑같은 것을 볼 수 있다
softmax(a)

array([0.01821127, 0.24519181, 0.73659691])

$softmax$ 함수 튜닝하기

In [6]:
big_a = np.array([1010, 1000, 990])
print(softmax(big_a))

[nan nan nan]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.


## 오버플로우 발생 원인

$exp$함수는 지수함수이다. $e^{10}$ 은 약 20,000 이고, $e^{100}$은 0이 40개 넘어가고, $e^{1000}$은 컴퓨팅 시스템에서 무한대를 의미하는 $inf$를 의미

해결하기 위해서 $log$를 활용한다. 참고로 지수함수에서의 $log$는 뺄셈을 의미한다.


$$
y_k = \frac{exp(a_k)}{\sum_{i=1}^n exp(a_i)} = \frac{C\,exp(a_k)}{C\,\sum_{i=1}^n exp(a_i)} = \frac{exp(a_k+logC)}{\sum_{i=1}^n exp(a_i+logC)} = \frac{exp(a_k+C^\prime)}{\sum_{i=1}^n exp(a_i+C^\prime)} 
$$

1. 분자와 분모에 $C$라는 임의의 정수를 곱합니다.
2. $C$를 지수 함수 $exp$안으로 옮겨서 $log C$로 만들어 준다.
3. $log C$를 $C^{'}$ 이라는 새로운 기호로 바꿔준다.

In [7]:
# 보통 상수 C는 입력값 중에 제일 큰값으로 선정한다.
c = np.max(big_a)
print(big_a - c)

[  0 -10 -20]


In [8]:
print(np.exp(big_a - c) / np.sum(np.exp(big_a - c)))

[9.99954600e-01 4.53978686e-05 2.06106005e-09]


In [9]:
def softmax(a):
  c = np.max(a) # 상수 c 구하기( 입력의 최댓값 )
  exp_a = np.exp( a - c ) # a + log C

  sum_exp_a = np.sum(exp_a)
  y = exp_a / sum_exp_a

  return y

In [10]:
big_y = softmax(big_a)
print("softmax 결과 : {}".format(big_y))
print("softmax 총합 : {}".format(np.sum(big_y)))

softmax 결과 : [9.99954600e-01 4.53978686e-05 2.06106005e-09]
softmax 총합 : 1.0


In [11]:
y = softmax(a)
print("softmax 결과 : {}".format(y))
print("softmax 총합 : {}".format(np.sum(y)))

softmax 결과 : [0.01821127 0.24519181 0.73659691]
softmax 총합 : 1.0
