<a href="https://colab.research.google.com/github/wjh818/Data_hwj/blob/main/Deep_Learning/9_Tensorflow_%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor란?

Tensor : 배열

* 배열인데 Rank 시스템이 있음
* 0 Rank Tensor - Scalar - 상수
* 1 Rank Tensor - Array (Vector)  - 1차원 배열
* 2 Rank Tensor - Matrix - 행렬
* 3 Rank Tensor - Tensor - 3차원 배열
* 4 Rank Tensor - Tensor - 4차원 배열 ...

# TensorFlow는?
* Tensor가 지나다닐 수 있는 **계산그래프**를 만들어 놓고 Tensor를 흘려(Flow) 보낸다.

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# 각종 시퀀스들을 Tensor로 변환이 가능

#1. list -> tensor
tf.constant([1, 2, 3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [3]:
# 2. tuple -> tensor
tf.constant((1, 2, 3))

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [4]:
# 3. ndarray -> tensor
arr = np.array([1, 2, 3])
tf.constant(arr)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 3])>

# Tensor 정보 확인하기

In [5]:
tensor = tf.constant(np.array([1, 2, 3]))
tensor.shape

TensorShape([3])

In [6]:
tensor = tf.constant(np.arange(0, 10).reshape(2, 5))
tensor.shape

TensorShape([2, 5])

In [7]:
tensor.dtype

tf.int64

In [8]:
tensor = tf.constant(np.random.randn(2, 3))
tensor.dtype

tf.float64

In [9]:
# 텐서를 구성하는 원소 중 데이터 타입이 가장 큰 것이 텐서의 데이터 타입이 된다.
# 예를 들어 텐서에 정수와 실수가 섞여 있으면 텐서의 타입은 실수가 된다.

tensor = tf.constant([1, 2.1, 3])
tensor.dtype

tf.float32

In [10]:
# 강제로 데이터 타입을 지정
tensor = tf.constant([1, 2, 3], dtype=tf.float32)
tensor.dtype

tf.float32

In [11]:
# tf.cast 를 활용해서 텐서의 타입을 변경
tf.cast(tensor, tf.uint8).dtype

tf.uint8

In [12]:
# numpy와 tensorflow는 상호간에 호환이 가능

# 1. tensor를 ndarray로 바꿔보기
tensor.numpy()

array([1., 2., 3.], dtype=float32)

In [13]:
# np.array를 이용해서 tensor를 ndarray로 바꾸기
np.array(tensor)

array([1., 2., 3.], dtype=float32)

# Tensorflow의 난수 생성

In [14]:
# numpy로 정규분포 만들기
np.random.randn(9)

array([-0.61992001, -0.1414743 , -0.61628816,  0.38793401,  1.42940231,
        0.77543513, -0.97053736,  0.71848298, -0.28880426])

In [15]:
# tensorflow로 정규분포 만들기
tf.random.normal((3, 3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.3838526 , -0.7821761 ,  0.8474799 ],
       [ 0.229187  , -2.8187437 , -0.07250632],
       [ 1.3739386 , -0.587615  , -0.9468933 ]], dtype=float32)>

In [16]:
# tensorflow로 균등분포 만들기
tf.random.uniform((3, 3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.6669053 , 0.9245471 , 0.7182696 ],
       [0.19897723, 0.6862745 , 0.2687949 ],
       [0.6152959 , 0.5118426 , 0.7296634 ]], dtype=float32)>

# Tensorflow로 One Hot Encoding

In [17]:
from tensorflow.keras.utils import to_categorical

In [18]:
to_categorical(1, 5)

array([0., 1., 0., 0., 0.], dtype=float32)